baseURL = "https://judsys.github.io"
languageCode = "en"
title = "JUDSYS"
theme = "hyde"

DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[params]
  themeColor = "theme-base-0d"
  copyright = "G. Queiroz"

[languages]
  [languages.en]
    title = "JUDSYS"
    description = "A digital signature standard for the common folks."
    languageName = "🇬🇧 English"
    weight = 1
    #copyright = "G. Queiroz"
  [[languages.en.menu.main]]
    url    = "/en/about"
    name   = "About"
    weight = 0
  [languages.pt]
    title = "JUDSYS"
    description = "Um padrão de assiantura digital para pessoas comuns."
    languageName = "🇧🇷 Português"
    weight = 2
  [[languages.pt.menu.main]]
    url    = "/pt/about"
    name   = "Sobre"
    weight = 0
